**Discente:** Paulo Guilherme Silva de Araújo

**Turma:** Engenharia de Computação - 2° período (Turma B)

 **Questão 1:**
 
 Para adicionar a biblioteca **numpy**, pode-se usar:

In [2]:
import numpy as np

**Questão 2:**

Vetorização é a forma como o numpy realiza as operações, como um vetor matemático, elemento a elemento.

Broadcasting é a relação de posição dos elementos de um vetor para fazer alguma determinada operação.

**Questão 3:**

Array é uma coleção de vários elementos, do mesmo tipo, que podem ser identificados por seu índice.

Lista é uma coleção de elementos que podem ou não ser do mesmo tipo, mas que também são identificados por seu indice.

Dicionário é uma coleção de elementos de tipos variados que, diferente do array e da lista, são identificados por chaves associados a eles.

**Questão 4:**

In [3]:
M = np.array([[1,  6, 11], [2,  7, 12], [3,  8, 13],[4,  9, 14], [5, 10, 15]])
print(M)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [4]:
N = [[1,  6, 11], [2,  7, 12], [3,  8, 13],[4,  9, 14], [5, 10, 15]]
print(N)

[[1, 6, 11], [2, 7, 12], [3, 8, 13], [4, 9, 14], [5, 10, 15]]


**Questão 5:**

In [4]:
np.linspace(1, 20, 10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [9]:
np.arange(1, 21, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
D = np.diag([1, 2, 3])
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
